links added
ShYriy/TaskManager pull request #16
Opened 2021-05-24 12:41 UTC by ShYriy

2021-05-24 19:23 UTC, greybutton requested changes

2021-05-24 19:23 UTC, greybutton commented on app/views/layouts/application.html.slim
> +    = link_to "Sign up", new_developer_path, class: 'mdl-navigation__link'
здесь отступ нужен больше, чтобы блок оказался внутри nav.mdl-navigation

2021-06-19 18:24 UTC, ShYriy commented on app/views/layouts/application.html.slim
> +    = link_to "Sign up", new_developer_path, class: 'mdl-navigation__link'
Всё исправил, тесты проходят, сервер запускается , но браузер не видит локалхост , "Safari can't open the page "lockalhost:8080/board" because Safari can"t connect to the server localhost". Не пойму в чём причина, искал, пока решения не нашёл.

2021-08-20 19:48 UTC, greybutton commented on app/views/layouts/application.html.slim
> +    = link_to "Sign up", new_developer_path, class: 'mdl-navigation__link'
возможно потому что поменял порт в `config/puma.rb`, попробуй вернуть как было

2021-08-20 19:49 UTC, greybutton requested changes
вернуть порт и перенести nav.mdl-navigation из под футера под .mdl-layout-spacer

2021-09-28 17:56 UTC, greybutton approved these changes

2021-09-28 20:24 UTC, merged