Feature/models
ShYriy/TaskManager pull request #7
Opened 2021-03-12 12:03 UTC by ShYriy

Не уверен правильно ли . rails test test/models/user_test.rb и rails test test/models/task_test.rb проходят ,  а bin/rails test
выдаёт ошибку : 
DeveloperTest#test_create:
ActiveRecord::RecordInvalid: Validation failed: Password can't be blank
    test/models/developer_test.rb:5:in `block in <class:DeveloperTest>'

2021-04-14 10:02 UTC, Andrew8xx8 requested changes

2021-04-14 10:02 UTC, Andrew8xx8 commented on test/factories/tasks.rb
> +    author_id { 1 }
Это некорректно, что фабрика инициализируется всегда 1. Записи с id 1, не будет. Здесь нужно создавать или билдить юзера, например через ассоциации или через `create` | `build`. Посмотри документацию `factory_bot`

2021-04-19 20:57 UTC, ShYriy commented
Пофиксил, все тесты проходят.

2021-04-21 07:41 UTC, greybutton commented
у тебя работа с ветками не верная во всех PR. Если делаешь сразу несколько уроков, то ветки должны создаваться друг от друга и PR делаться в родительскую ветку, но сливать ветки только в develop (меняя перед самым мерджем, если предыдущие заапрувлены и смержены)

2021-04-22 12:58 UTC, closed without merging